### ISSUE TITLE
Optional rbenv

### ISSUE THREAD

**Issue by wlads** [noahgibbs/madscience#11]
How about create a feasible way to change the ruby versioning system, like `--rvm or --rbenv` or maybe even check which one is installed and run accordingly.

I'm proposing this feature bc **I'm using rbenv** on OS X and since **rbenv** and **RVM** are [_incompatible_](https://github.com/sstephenson/rbenv#installation) and also don't want to switch them, would madscience work in my dev environment? If not, It could be used only to deploy to the cloud? If it's the case, how its better than a direct capistrano provisioning e.g. [mattbrictson/capistrano-fiftyfive](https://github.com/mattbrictson/capistrano-fiftyfive) besides the underlying tools?

Let me known your thoughts on this if it's is on your roadmap and even if makes sense!
Liked your approach to simplify those deployments grieves :smile:

**Comment by noahgibbs** [comment]
Unfortunately, changing whether rvm or rbenv is used on the guest VM is a huge, far-reaching thing. It touches a very high percentage of the code.

However, you should be able to use either one on your development machine right now, without a problem. RVM isn't mandatory to running madscience, it's just compatible with it.

**Comment by noahgibbs** [comment]
Okay, I've added a section to the README saying that I won't be using rbenv on the Guest VM, but it's fine on the host.

**Comment by noahgibbs** [comment]
Also, in response to "why is it better than capistrano-fiftyfive?", the short answer is "you can use Chef cookbooks, and there are a lot of those for deployment." You can also use Capistrano tasks, of course. But there aren't usually good Capistrano tasks for deploying software, and in general Cap lacks a lot of the good parts of a real server config tool (like Chef, Puppet, Ansible or Salt.)

Also, if you do your server configuration and your deployment both through Cap, you have to run Cap as root, which means your app deploy has to be done as root.
