### ISSUE TITLE
Hang on gem install

### ISSUE THREAD

**Issue by michaelachrisco** [noahgibbs/madscience#13]
I am seeing a huge spike in CPU at gem install on OSX10.10
Ruby 2.2.1

References: https://github.com/chef/libyajl2-gem/issues/5

I suppose I can install by running --no-doc via `gem install madscience --no-doc`
but I wonder if anyone else is having this issue?

**Comment by noahgibbs** [comment]
I haven't, but others might be.

**Comment by michaelachrisco** [comment]
When I control^C out:

``` Bash
$ gem uninstall madscience
$ gem clean 
Cleaning up installed gems...
Clean Up Complete

$ gem install madscience
Successfully installed madscience-0.0.20
Parsing documentation for madscience-0.0.20
Done installing documentation for madscience after 0 seconds
1 gem installed

$ madscience
$ fatal: Not a git repository (or any of the parent directories): .git
/Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find blanket_wrapper-1.1.0 in any of the sources (Bundler::GemNotFound)
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/spec_set.rb:85:in `map!'
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/spec_set.rb:85:in `materialize'
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/definition.rb:132:in `specs'
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/definition.rb:177:in `specs_for'
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/definition.rb:166:in `requested_specs'
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/environment.rb:18:in `requested_specs'
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:13:in `setup'
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler.rb:122:in `setup'
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1/gems/madscience-0.0.20/bin/madscience:49:in `block in <top (required)>'
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1/gems/madscience-0.0.20/bin/madscience:42:in `in_madscience_dir'
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1/gems/madscience-0.0.20/bin/madscience:49:in `<top (required)>'
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1/bin/madscience:23:in `load'
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1/bin/madscience:23:in `<main>'
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by noahgibbs** [comment]
The "not a git repository" message is standard and annoying. I'm not even sure what blanket_wrapper is, though. I don't use it (says my Gemfile.lock.)

Have you perhaps installed something that's using it automatically in a Rubygems or Bundler plugin?

**Comment by noahgibbs** [comment]
Ah. It looks like it may be looking for the MadScience stuff in the wrong place, and it's trying to run Bundler.setup incorrectly somehow. I'll review that code and see if there's an obvious way for it to go wrong.

It looks like madscience is installed under an RVM gems directory -- the same way I do it. So that's not the problem.

**Comment by noahgibbs** [comment]
Hm. Dir.chdir should raise an exception if you give an incorrect directory to it. So I can't be just picking the directory wrong. So Bundler.setup _should_ be running under your RVM madscience-0.0.20 directory. But then why is it looking for the blanket_wrapper gem? My Gemfile certainly doesn't use it, directly or indirectly.

Is it possible you've set one of the Bundler environment variables that changes the Gemfile being used? BUNDLE_GEMFILE or something similar?

**Comment by michaelachrisco** [comment]
For future reference: 

`gem install libyajl2 --no-document` 'fixed' the issue.

I don't think this is a bug but rather something on my local system. I am closing.
