### ISSUE TITLE
New install got: "fatal: reference is not a tree"

### ISSUE THREAD

**Issue by saturnflyer** [noahgibbs/madscience#14]
I have an existing git repository where I'm trying to setup madscience.

Here's what I get:

```
sudo /Users/jim/.gem/ruby/2.2.1/bin/madscience setup
WARN: Unresolved specs during Gem::Specification.reset:
      mime-types (~> 2.0)
      ffi (~> 1.5, ~> 1.9)
      rake (>= 10.0.0, ~> 10.1)
      rack (>= 0)
      pry (~> 0.9)
      thor (~> 0.15)
      i18n (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Installing apt (2.6.0)
Installing chef_handler (1.1.6)
Installing dmg (2.2.2)
Installing windows (1.36.1)
Installing vagrant (0.2.1)
fatal: reference is not a tree: e58eec18bbe960e000f3eb17434c1e87428a6ddf
fatal: Not a git repository (or any of the parent directories): .git
/Users/jim/.gem/ruby/2.2.0/gems/chef-12.0.3/lib/chef/data_bag_item.rb:161: warning: circular argument reference - data_bag
Starting Chef Client, version 12.0.3
Compiling Cookbooks...

Running handlers:
[2015-03-31T11:52:34-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-03-31T11:52:34-04:00] ERROR: Exception handlers complete
[2015-03-31T11:52:34-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 4.95742 seconds
[2015-03-31T11:52:34-04:00] ERROR: Cookbook vagrant not found. If you're loading vagrant from another cookbook, make sure you configure the dependency in your metadata
[2015-03-31T11:52:35-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

I'm unsure of cause of this.

I'm using `chruby` so the `rvmsudo` command is not present.

**Comment by noahgibbs** [comment]
Hm. "Cookbook vagrant not found" means something failed earlier, usually in the librarian run.

The "Unresolved specs", "circular reference" and "not a git repository" things are annoying, but fine.

So it looks like the actual error was silent, and occurred during "compiling cookbooks" or "running handlers."

**Comment by noahgibbs** [comment]
Ah, sorry, yes -- died when trying to install vagrant cookbook. "Reference is not a tree" sounds like there was a problem when doing the git-clone on that cookbook from my GitHub profile. My best advice right now is "run it again" :-/

**Comment by saturnflyer** [comment]
Ok. Re-running a few times yields the same.

**Comment by noahgibbs** [comment]
Do me a favor and delete everything under the "cookbooks" directory and try again. This sounds like a botched git clone for the cookbook, but apparently it's not getting fixed :-(

**Comment by saturnflyer** [comment]
I think there's a mismatch here and I must be doing something wrong.

I have no cookbooks directory. Do I need to clone this repo?

These are the steps I took:
1. gem install madscience
2. sudo madscience setup

**Comment by noahgibbs** [comment]
Sorry, I wasn't clear. There's a cookbooks directory in the gem itself, where "madscience" is installed. That directory seems like it has a botched git repo inside it, probably in the "vagrant" cookbook.

So you'd need to run "gem env" to see where the madscience gem is installed and fix it there.

I haven't been packaging those cookbooks with the gem, but it's starting to seem like I need to. Librarian isn't doing a good job of reliably checking them out on end-user machines :-(

**Comment by noahgibbs** [comment]
Alternately, uninstall and reinstall the gem.

I'll start adding those cookbooks to the gem before pushing, which should make this a non-issue in madscience 0.0.22 and higher.

**Comment by saturnflyer** [comment]
No luck. I tried clearing the contents of the "cookbooks" directory in the gem and rerunning the commands. I tried uninstalling and reinstalling.
Doubt it matters but ruby on my machine is `ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin13]`

**Comment by noahgibbs** [comment]
I've pushed 0.0.23, which should run with pre-cloned cookbooks. Give that a try.

**Comment by noahgibbs** [comment]
Hm. Also, which Git version are you running? I hope it doesn't matter, but if something's wonky there then you'll have the same problem even if you just directly clone the cookbook from GitHub...

**Comment by saturnflyer** [comment]
`git version 2.2.1`

Uninstalled madscience. Reinstalled. Same problem :-/

Thanks for helping me debug this by the way.
I'm currently upgrading to git 2.2.2 to see if that does anything.

**Comment by noahgibbs** [comment]
Very happy to! Thanks for trying MadScience and giving me a chance to whittle away problems ;-)

Presumably you no longer see the "not a tree reference" error after "installing vagrant (0.2.1)" since there's now no librarian run happening. So you shouldn't still be seeing "installing vagrant (0.2.1)"

Hm. I wonder if I'm somehow caching a Git reference that is no longer used somewhere... I've eliminated all the obvious-to-me ways to do that, but maybe I'm missing something. I'll see what I can find there.

**Comment by saturnflyer** [comment]
Still seeing it install vagrant 0.2.1

```
gem install madscience
Fetching: madscience-0.0.23.gem (100%)
Successfully installed madscience-0.0.23
1 gem installed
bump:ruby jim$ sudo madscience setup
WARN: Unresolved specs during Gem::Specification.reset:
      mime-types (~> 2.0)
      ffi (~> 1.5, ~> 1.9)
      rake (>= 10.0.0, ~> 10.1)
      rack (>= 0)
      pry (~> 0.9)
      thor (~> 0.15)
      i18n (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Installing apt (2.6.0)
Installing chef_handler (1.1.6)
Installing dmg (2.2.2)
Installing windows (1.36.1)
Installing vagrant (0.2.1)
fatal: reference is not a tree: e58eec18bbe960e000f3eb17434c1e87428a6ddf
fatal: Not a git repository (or any of the parent directories): .git
/Users/jim/.gem/ruby/2.2.0/gems/chef-12.0.3/lib/chef/data_bag_item.rb:161: warning: circular argument reference - data_bag
Starting Chef Client, version 12.0.3
Compiling Cookbooks...

Running handlers:
[2015-03-31T15:46:19-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-03-31T15:46:19-04:00] ERROR: Exception handlers complete
[2015-03-31T15:46:19-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 5.019593 seconds
[2015-03-31T15:46:19-04:00] ERROR: Cookbook vagrant not found. If you're loading vagrant from another cookbook, make sure you configure the dependency in your metadata
[2015-03-31T15:46:19-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by noahgibbs** [comment]
Huh. Now _that's_ interesting. That Git SHA isn't a current one. It's from one (checked in) revision of the Cheffile.lock ago. So it's not in the Git repo. But I wonder how you're getting a copy of it? Time for me to start manually downloading gems and unpacking files in them.

Do me a favor and run "madscience --version"?

**Comment by noahgibbs** [comment]
By the way -- if "madscience --version" says there's no such command, that will be another piece of information strongly suggesting that you are running an older version of madscience with sudo. That may have to do with problems in your path/gempath/etc.

**Comment by noahgibbs** [comment]
Okay. Then it's _also_ time for me to start printing the version of the madscience gem at the start of each run, and writing a file into the repo with the version. I needed to do that second one anyway, but I think this just convinced me of the first one, too :-)

**Comment by noahgibbs** [comment]
You can check some of this by running "sudo gem env" and seeing if the environment looks sane, by the way. You can compare to just "gem env" as well and see if "sudo gem env" can run gems installed with just "gem env".

**Comment by saturnflyer** [comment]
```
$ madscience --version
0.0.23
```

Hmm. My environments are definitely different. Without `sudo`

```
  - GEM PATHS:
     - /Users/jim/.gem/ruby/2.2.1
     - /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0
```

And with `sudo`:

```
  - GEM PATHS:
     - /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0
     - /Users/jim/.gem/ruby/2.2.0
```

I'm going to try to wipe out ruby version 2.2.0 and see what that does.

Here's the whole thing.

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5
  - RUBY VERSION: 2.2.1 (2015-02-26 patchlevel 85) [x86_64-darwin13]
  - INSTALLATION DIRECTORY: /Users/jim/.gem/ruby/2.2.1
  - RUBY EXECUTABLE: /Users/jim/.rubies/ruby-2.2.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/jim/.gem/ruby/2.2.1/bin
  - SPEC CACHE DIRECTORY: /Users/jim/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/jim/.rubies/ruby-2.2.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-13
  - GEM PATHS:
     - /Users/jim/.gem/ruby/2.2.1
     - /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :benchmark => false
     - "gem" => "--no-ri --no-rdoc"
     - :sources => ["http://rubygems.org"]
  - REMOTE SOURCES:
     - http://rubygems.org
  - SHELL PATH:
     - /Users/jim/.gem/ruby/2.2.1/bin
     - /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin
     - /Users/jim/.rubies/ruby-2.2.1/bin
     - /usr/local/heroku/bin
     - /usr/local/bin
     - /usr/local/share/npm/bin
     - /usr/local/sbin
     - /Applications/Postgres.app/Contents/Versions/9.3/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - /usr/texbin
bump:madscience jim$ sudo gem env
Password:
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5
  - RUBY VERSION: 2.2.1 (2015-02-26 patchlevel 85) [x86_64-darwin13]
  - INSTALLATION DIRECTORY: /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0
  - RUBY EXECUTABLE: /Users/jim/.rubies/ruby-2.2.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/jim/.rubies/ruby-2.2.1/bin
  - SPEC CACHE DIRECTORY: /Users/jim/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/jim/.rubies/ruby-2.2.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-13
  - GEM PATHS:
     - /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0
     - /Users/jim/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :benchmark => false
     - "gem" => "--no-ri --no-rdoc"
     - :sources => ["http://rubygems.org"]
  - REMOTE SOURCES:
     - http://rubygems.org
  - SHELL PATH:
     - /Users/jim/.gem/ruby/2.2.1/bin
     - /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin
     - /Users/jim/.rubies/ruby-2.2.1/bin
     - /usr/local/heroku/bin
     - /usr/local/bin
     - /usr/local/share/npm/bin
     - /usr/local/sbin
     - /Applications/Postgres.app/Contents/Versions/9.3/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - /usr/texbin
$ sudo gem env
Password:
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5
  - RUBY VERSION: 2.2.1 (2015-02-26 patchlevel 85) [x86_64-darwin13]
  - INSTALLATION DIRECTORY: /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0
  - RUBY EXECUTABLE: /Users/jim/.rubies/ruby-2.2.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/jim/.rubies/ruby-2.2.1/bin
  - SPEC CACHE DIRECTORY: /Users/jim/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/jim/.rubies/ruby-2.2.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-13
  - GEM PATHS:
     - /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0
     - /Users/jim/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :benchmark => false
     - "gem" => "--no-ri --no-rdoc"
     - :sources => ["http://rubygems.org"]
  - REMOTE SOURCES:
     - http://rubygems.org
  - SHELL PATH:
     - /Users/jim/.gem/ruby/2.2.1/bin
     - /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin
     - /Users/jim/.rubies/ruby-2.2.1/bin
     - /usr/local/heroku/bin
     - /usr/local/bin
     - /usr/local/share/npm/bin
     - /usr/local/sbin
     - /Applications/Postgres.app/Contents/Versions/9.3/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - /usr/texbin
```

**Comment by noahgibbs** [comment]
There's a common problem with sudo where it doesn't propagate the normal environment variables that Ruby uses. That's why you use rvmsudo for rvm.

One way to fix this would be to "sudo gem install madscience" -- it will put a current version of madscience wherever sudo is pulling gems from.

Looks like it's also time for me to do some research on chruby. I know there are potential problems with other version managers, but I'm not sure how they usually solve the rvmsudo problem.

I'm also considering building in a horrible hack that pulls all Ruby-relevant env variables and then runs sudo in a way that will set them on the other side... But "sudo madscience construct" is so _nice_-looking now... Dunno. I'm thinking that having four+ sets of alternate instructions for different version managers may get bad fast, though.

**Comment by noahgibbs** [comment]
Huh. Weird. You also have a funny-looking thing going on with the install directory: "/Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0". It's under Ruby 2.2.1, but using the gems/2.2.0 directory. That might be legitimate, but certainly looks shady.

**Comment by saturnflyer** [comment]
I agree that complicating things will make this messy... And I knew I might get into trouble not being on the blessed rvm path.
It may be that I just haven't set my default Ruby environment up properly. Usually I keep my default to the latest.
I'll continue and report back here

**Comment by noahgibbs** [comment]
Oh! Yeah, "sudo gem install madscience" won't help you because you have something in the GEM_PATH that's ahead of the gem install dir. So the older version which somehow got into "/Users/jim/.gem/ruby/2.2.0" will always take precedence over the one you can actually see.

Interesting. Not sure how that happened, but clearing out any madscience gems under ~/.gem/ruby/2.2.0 may fix it.

**Comment by noahgibbs** [comment]
Okay, pushed MadScience 0.0.24. It prints the gem version right up top on every run -- that would have detected your problem. It also writes a file with debug details into every repo cloned by the MadScience gem, which would have detected your problem retroactively if you hadn't saved the console output.

**Comment by saturnflyer** [comment]
Thanks. This definitely is because my system is somehow screwed up. I'm currently trying to clear out my gem path settings and reinstalling ruby.

**Comment by noahgibbs** [comment]
Sounds good. And I'm getting a fairly weird error separately, which seems to have been caused when I upgraded to Chef 12, yet I somehow didn't see it until now... Weird. So I'll work on that part ;-)

**Comment by noahgibbs** [comment]
Okay. Jim's found his problem and I've filed and fixed a different bug from here. Closing this.

**Comment by saturnflyer** [comment]
For anyone following along, I looked further into my gem path problems and found this http://stackoverflow.com/questions/2975206/how-to-delete-a-gem-path which is basically summed up to 
"how do I remove a gem path?" "you can't"

**Comment by noahgibbs** [comment]
Yup. You can, however, delete gems that are at that path! :-)

**Comment by saturnflyer** [comment]
That's what I expected too. Oddly, it was still looking for gems there and failed. It didn't failover to the alternate path

**Comment by noahgibbs** [comment]
That's really odd. Normally it should check all parts of the gem path, but just use the first ones first.

You must have had _something_ there, though, right? You weren't just getting the new gem version ignored, you were using an older version in preference to it.
