### ISSUE TITLE
Linode Support

### ISSUE THREAD

**Issue by noahgibbs** [noahgibbs/madscience#4]
This will be straightforward, I hope. The Vagrant plugin is already installed via the MadScience gem.

Should be a lot like Digital Ocean.

**Comment by michaelachrisco** [comment]
Personally would love this :+1:

**Comment by noahgibbs** [comment]
Excellent. It's very much in the plans :-)

**Comment by noahgibbs** [comment]
First draft is in, but more debugging to do.

**Comment by michaelachrisco** [comment]
Cool, I can test on a new box if need be :)

**Comment by noahgibbs** [comment]
Deploying to Linode and running Chef/Cap now works, but haven't tested all the details.

**Comment by noahgibbs** [comment]
That is, I think this works :-)
